create table account
(
    account_id integer generated by default as identity
        primary key,
    username   varchar(30) not null,
    email      varchar     not null,
    password   varchar     not null,
    role       varchar
);
create table pet
(
    pet_id     integer generated by default as identity
        primary key,
    account_id integer
        references account,
    name       varchar          not null,
    breed      varchar          not null,
    age        double precision not null,
    photo_url  varchar
);
create table photos
(
    photo_id    integer generated by default as identity
        primary key,
    pet_id      integer
        references pet,
    url         varchar not null,
    description varchar,
    upload_date timestamp(0)
);
create table post
(
    post_id    integer generated by default as identity
        primary key,
    account_id integer
        references account,
    text       varchar not null
);
create table post_photo
(
    post_photo_id integer generated by default as identity
        primary key,
    post_id       integer
        references post,
    photo_url     varchar not null,
    description   varchar(100),
    upload_date   timestamp(0)
);